sudo: false
language: node_js
node_js:
- '4.1'
- '4.0'
- iojs
- '0.12'
- '0.10'
env:
  global:
  - secure: bLyl4Fh8tFAODFB9OZJNQ1uTUa30DCHAIY3RFB9e9LRsR2mJ/vtn/G7HXhyFYbdNWkLfEhim4o9llCjjjl3jOurqJlrYkXUJAcF+tdGD6gEblGf8SeW4lt+W2uoLa+Nq5aZeUYMvIruxTT0tZWjwOJaILNy9SU2f2rVTIl3OY+Q=
  - secure: GacOQ945X2eoIr6RPJo452RP3pBZdlWcSI+fM4QJPPl+N7PJgo8a4qOhJgdB98urrHuuSEdKaFKKDrkyIKzSxwbUL0p4uCSmvjHUaCCgW6MS4vQZcyO7JehUsdpz3qDusmhYKVnPHtsCg3fnruwLxqbIp/ORsqwaDiu+aqijFGA=
  - secure: doqIAfUiYiFfYrOiiQN/nX3W60twiUqbYVqdQKOJa5VVV4Z4MzFM4zK/q61SJpvXwtiYQB9+Mf+RrYw/k2xw//12d+oySCbVk/4oWJQqcH/04nNkhHLaTJalSMdHDgPg2ZenaRyn76i6WGXTgPlH34tcBdJUIPWzynNJ9pcPWEs=
  - secure: HITeATI/OdaMknP0HWciv9aulspr7mCdZ3QgQ3nLDoQMAY0pftWC8nBmjReCNeh2ioS2GfMJX0Z62nbb7qWFztu8Q3fQdmf37qSIY8JLYoC3olDb53siEtQTUKbhhNBOEPTV6BbSEe/4X3rPZqmTWvujVtTiap2/WlDpIIYlgOc=
  - secure: fbgUzgFBIuPdFfLPdJHgGOU/Q4UOULDbdmIks5uxhzMj86QIjpZx3E7OM/3YNgSQoEmD+FetquW1WaRzUWwkA9bfMemDgAXxXxod8NhruWWk86ISG/jZsL7wbptYSMOzqBtAJzVjnFo5SdXWMTdfJTzuG2N+AYL/45WKjxi66/U=
