sudo: false
language: node_js
node_js:
- '4.1'
- '4.0'
- iojs
- '0.12'
- '0.10'
env:
  global:
  - secure: UONvroISwywiXsfxQOnpN+5JRyNK0pUfWVdnSoJoqfWR3HhNcA3XA8uZz4ruiIDXByLS2oPcez4Xpa4JGARntKsvcpRNyOMCOFjgiRk0xSBd1/ssF96elivGmX222gRwKMiBb2Ysa66/RORhXSqXdSgHshdGIr3aexhwXxoQNYk=
  - secure: KqyakYSEk3SZuTnYNeUytv2y4F/hZ6swwrtGpYp6mvuygP8ouglThX/z/MHYE3v+3QzN51lCRVnjrcYsO4fFkayCcKMSwEnu0oSaLf6PBaLmyArosjTtNuG6Btvx+6KVnSB6VGQUCdEGv30/Z/QqIur3/FPqD8oO905sqDSbxJY=
  - secure: TanpRvD3PQ9QSUqXYI72q+DQY/uawsGp9xyEF48qphsJQYnFgbWa5k/+c3M+UbgpymoXgZkWKJGGMQKwecn2+mmetadkfhajWXNEfewJn6349++CTydTsNCpUq7J1Nky5mM0O2djHrMcEsNKdaMo1HOMeXlRM0oLI3RxgERzGLo=
  - secure: cPBtMtfzfvIw4Hlhlx1uy5H73ABVvDkMyyM6DJ11gMhvSO62mHc4N92fBr2abr7bKewaQqAgQ59XBErAF/4+JhFnmBjbIWZPh0ITPyxICYBYXQExzLPpzKrbFQ0zhDC10xcli/DgDRVEgz6bjaAapmDGB8zSwLNNAOEEFNzvIwE=
